<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="54784" started-at="2017-06-07T09:50:16Z" finished-at="2017-06-07T09:51:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="54784" started-at="2017-06-07T09:50:16Z" finished-at="2017-06-07T09:51:11Z">
      <class name="co.rchive.test.spec.verifyemails.VerifySignUpEmailLinkTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:co.rchive.test.spec.verifyemails.VerifySignUpEmailLinkTest@1593948d]" name="setUp" is-config="true" duration-ms="13198" started-at="2017-06-07T15:20:16Z" finished-at="2017-06-07T15:20:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyEmailforSignUp()[pri:0, instance:co.rchive.test.spec.verifyemails.VerifySignUpEmailLinkTest@1593948d]" name="verifyEmailforSignUp" duration-ms="40712" started-at="2017-06-07T15:20:29Z" finished-at="2017-06-07T15:21:10Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at co.rchive.spec.verifyemails.VerifyEmailSpecDefinition.clickSignUpLink(VerifyEmailSpecDefinition.java:35)
	at co.rchive.test.spec.verifyemails.VerifySignUpEmailLinkTest.verifyEmailforSignUp(VerifySignUpEmailLinkTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEmailforSignUp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:co.rchive.test.spec.verifyemails.VerifySignUpEmailLinkTest@1593948d]" name="tearDown" is-config="true" duration-ms="794" started-at="2017-06-07T15:21:10Z" finished-at="2017-06-07T15:21:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- co.rchive.test.spec.verifyemails.VerifySignUpEmailLinkTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
